LogLevel warn
PageLogFormat
MaxLogSize 0
Listen /run/cups/cups.sock
WebInterface No
Browsing Off
DefaultAuthType Basic
JobPrivateAccess default
JobPrivateValues default
SubscriptionPrivateAccess default
SubscriptionPrivateValues default
DefaultPolicy default
<Policy default>
  <Limit All>
    Order deny,allow
    Allow localhost
  </Limit>
</Policy>
