# Generated by Django 5.2.17 on 2026-09-04 01:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning')], default='unknown', max_length=16)),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('mdns', 'AirPrint / AirScan'), ('lan', 'LAN scan')], max_length=8)),
                ('cidr', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('results', models.JSONField(blank=True, default=list)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovery_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrinterEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(max_length=500, unique=True)),
                ('queue_name', models.SlugField(max_length=80, unique=True)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('default_options', models.JSONField(blank=True, default=dict)),
                ('accepting_jobs', models.BooleanField(default=True)),
                ('queue_enabled', models.BooleanField(default=True)),
                ('queued_jobs', models.PositiveIntegerField(default=0)),
                ('supplies', models.JSONField(blank=True, default=list)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer', to='manager.device')),
            ],
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('source_path', models.CharField(max_length=500)),
                ('normalized_path', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('cups_job_id', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('converting', 'Converting'), ('submitted', 'Submitted'), ('held', 'Held'), ('printing', 'Printing'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('artifact_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='manager.printerendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannerEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(max_length=500, unique=True)),
                ('protocol', models.CharField(choices=[('escl', 'eSCL / AirScan'), ('wsd', 'WSD')], default='escl', max_length=8)),
                ('sane_name', models.CharField(blank=True, max_length=180)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scanner', to='manager.device')),
            ],
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('result_path', models.CharField(blank=True, max_length=500)),
                ('output_format', models.CharField(default='pdf', max_length=12)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('processing', 'Processing'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('artifact_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_jobs', to=settings.AUTH_USER_MODEL)),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='manager.scannerendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('run_after', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_owner', models.CharField(blank=True, max_length=100)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['state', 'run_after'], name='manager_tas_state_b0ad64_idx')],
            },
        ),
    ]
