# Generated by Django 5.2.17 on 2026-09-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerendpoint',
            name='uri',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
